name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4

      - name: "📚 Fetch Hashnode Blog Posts"
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://network-nitish.hashnode.dev/rss.xml,https://hackathon-nitish.hashnode.dev/rss.xml"
          max_post_count: 5
          template: '<table><tr><td>🔗 <strong><a href="$url">$title</a></strong><br/><sub>📅 $date</sub><br/><p>$description</p></td></tr></table>$newline'
          comment_tag_name: "BLOG-POST-LIST"
